

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Toshiba
 */
public class DitaPrihatini_Tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form DitaPrihatini_Tugas2
     */
    public DitaPrihatini_Tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSoal2 = new javax.swing.JRadioButton();
        jSoal3 = new javax.swing.JRadioButton();
        jSoal4 = new javax.swing.JRadioButton();
        jSoal = new javax.swing.JTextField();
        jHitung = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jJawaban = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jNilaiA = new javax.swing.JTextField();
        jNilaiN = new javax.swing.JTextField();
        jNilaiX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 30)); // NOI18N
        jLabel6.setText("TUGAS 2 ASISTENSI ALPRO");

        jSoal2.setBackground(new java.awt.Color(255, 255, 255));
        jSoal2.setText("Soal No 2");
        jSoal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoal2ActionPerformed(evt);
            }
        });

        jSoal3.setBackground(new java.awt.Color(255, 255, 255));
        jSoal3.setText("Soal No 3");
        jSoal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoal3ActionPerformed(evt);
            }
        });

        jSoal4.setBackground(new java.awt.Color(255, 255, 255));
        jSoal4.setText("Soal No 4");
        jSoal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoal4ActionPerformed(evt);
            }
        });

        jSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoalActionPerformed(evt);
            }
        });

        jHitung.setText("Hitung");
        jHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHitungActionPerformed(evt);
            }
        });

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJawabanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 25)); // NOI18N
        jLabel1.setText("Hasil");

        jNilaiA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNilaiAActionPerformed(evt);
            }
        });

        jNilaiN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNilaiNActionPerformed(evt);
            }
        });

        jNilaiX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNilaiXActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setText("Nilai n :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setText("Nilai a :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Nilai x :");

        jLabel5.setText("Nb = Jika ingin mengganti soal, tekan reset lalu putihkan kembali lubang yang telah dihitamkan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSoal4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSoal2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jSoal3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNilaiN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSoal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSoal3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSoal4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSoal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jJawaban))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNilaiN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSoal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoal3ActionPerformed
    jNilaiA.setText("");
    jNilaiN.setText(null);
    jNilaiX.setText("");
    jJawaban.setText(null);
    jSoal.setText("f(x) = cosh(-6x)");
    }//GEN-LAST:event_jSoal3ActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
    this.dispose();
    }//GEN-LAST:event_jExitActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
    jNilaiA.setText("");
    jNilaiN.setText(null);
    jNilaiX.setText("");
    jJawaban.setText(null);
    jSoal.setText(null);
    }//GEN-LAST:event_jResetActionPerformed

    private void jSoal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoal2ActionPerformed
    jNilaiA.setText("");
    jNilaiN.setText(null);
    jNilaiX.setText("");
    jJawaban.setText(null);
    jSoal.setText("f(x) =  sin(2x)");
    }//GEN-LAST:event_jSoal2ActionPerformed

    private void jSoal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoal4ActionPerformed
    jNilaiA.setText("");
    jNilaiN.setText(null);
    jNilaiX.setText("");
    jJawaban.setText(null);
    jSoal.setText("f(x) = ln(-x)");
    }//GEN-LAST:event_jSoal4ActionPerformed

    private void jSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSoalActionPerformed

    private void jNilaiAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNilaiAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNilaiAActionPerformed

    private void jNilaiNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNilaiNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNilaiNActionPerformed

    private void jNilaiXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNilaiXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNilaiXActionPerformed

    //Mendapatkan Faktorial
    public static double faktorial(int number){
        if(number==1 || number==0){
            return 1;
        }else{
            return number * faktorial(number-1);
        }
        }
    //Menghitung Soal No 2
    public static double hitungsoal2(double a, double n, double x){
        double[] f = new double[10001];
        double es = 0.5 * Math.pow(10, 2-n);
        double function = 0;
        f[0] = Math.sin(Math.toRadians(2*a));
        for (int i=1; i<= 10000; i++){
        f[i] = f[i-1] + ((Math.pow(-2,i)*Math.sin(Math.toRadians(2*a))*
                Math.pow(Math.toRadians(x-a),2*i))/faktorial(2*i));
        double ea = ((f[i]-f[i-1])/f[i])*100;
        if(Math.abs(ea)<es){
            function += f[i];
            break;
        }
        }
    //Hasil Soal No 2
    double hasil2 = function;
        return hasil2;
        }
    
    //Menghitung Soal No 3
    public static double hitungsoal3(double a, double n, double x){
        double[] f = new double[10001];
        double function = 0;
        double es = 0.5 * Math.pow(10, 2-n);
        f[0] = (Math.exp(6*a)+Math.exp(-6*a))/2;
        for(int i=1; i<10000; i++){
            if(a!=0){
            f[i] = f[i-1] + ((Math.exp(6*a) + Math.pow(-1,i)*
                    Math.exp(-6*a))*(Math.pow(6,i)*
                    Math.pow(x-a,i)))/(2*(faktorial(i)));
            }else{
            f[i] = f[i-1] + Math.pow(6*x,2*i)/faktorial(2*i);
            }
            double ea = ((f[i]-f[i-1])/f[i])*100;
            if(Math.abs(ea)<es){
                function += f[i];
                break;
            }
        }
    //Hasil Soal No 3
    double hasil3 = function;
        return hasil3;
        }
    
    //Menghitung Soal No 4
    public static double hitungsoal4(double a, double n, double x){
        double[] f = new double[10001];
        double es = 0.5 * Math.pow(10, 2-n);
        double function = 0;
        f[0] = Math.log(-a);
        for(int i=1; i<=10000; i++){
            f[i] = f[i-1]+(Math.pow(-1,i+1)*Math.pow(x-a, i))/(i*Math.pow(a,i));
        double ea = ((f[i]-f[i-1])/f[i])*100;
        if(Math.abs(ea)<es){
        function += f[i];
        break;   
        }
    }
    //Hasil Soal No 4
    double hasil4 = function;
        return hasil4;
        }
    
    
    private void jHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHitungActionPerformed
    double a = Double.parseDouble(jNilaiA.getText());
    double n = Double.parseDouble(jNilaiN.getText());
    double x = Double.parseDouble(jNilaiX.getText());
    if(jSoal2.isSelected()){
        jJawaban.setText(String.valueOf(hitungsoal2(a,n,x)));
    }
    else if(jSoal3.isSelected()){
        jJawaban.setText(String.valueOf(hitungsoal3(a,n,x)));
    }
    if(jSoal4.isSelected()){
        jJawaban.setText(String.valueOf(hitungsoal4(a,n,x)));
    }
    }//GEN-LAST:event_jHitungActionPerformed

    private void jJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJawabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJawabanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DitaPrihatini_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DitaPrihatini_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DitaPrihatini_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DitaPrihatini_Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DitaPrihatini_Tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExit;
    private javax.swing.JButton jHitung;
    private javax.swing.JTextField jJawaban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNilaiA;
    private javax.swing.JTextField jNilaiN;
    private javax.swing.JTextField jNilaiX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jReset;
    private javax.swing.JTextField jSoal;
    private javax.swing.JRadioButton jSoal2;
    private javax.swing.JRadioButton jSoal3;
    private javax.swing.JRadioButton jSoal4;
    // End of variables declaration//GEN-END:variables
}
